# Generated by Django 5.0.7 on 2024-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebedores', '0002_recebedores_complemento_alter_recebedores_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebedores',
            name='cep',
            field=models.CharField(default='00000000', max_length=9),
        ),
    ]
