# Generated by Django 5.0.7 on 2024-08-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doador',
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
    ]
