# Generated by Django 5.0.7 on 2024-08-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_item', models.CharField(max_length=255)),
                ('tp_item', models.CharField(choices=[('COMIDA', 'comida'), ('ROUPA', 'roupa'), ('BRINQUEDOS', 'brinquedos'), ('HIGIENE', 'higiene'), ('BRINQUEDOS', 'brinquedos')], max_length=50)),
            ],
        ),
    ]
