# Generated by Django 5.0.7 on 2024-08-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0002_doacao_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacao_item', to='doacao.item'),
        ),
        migrations.CreateModel(
            name='Item_Doacao_Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_doacao', to='doacao.item')),
            ],
        ),
    ]
