# Generated by Django 5.0.7 on 2024-08-26 14:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0003_alter_doacao_item_item_item_doacao_rec'),
        ('recebedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgencia', models.CharField(choices=[('LEVE', 'leve'), ('MEDIA', 'media'), ('URGENTE', 'urgente')], max_length=50)),
                ('modo_entrega', models.CharField(choices=[('PRESENCIAL', 'presencial'), ('DELIVERY', 'delivery')], max_length=50)),
                ('status_doacao', models.CharField(choices=[('ABERTO', 'aberto'), ('FINALIZADO', 'finalizado'), ('CANCELADO', 'cancelado')], max_length=50)),
                ('data_abertura', models.DateTimeField(default=datetime.datetime.now)),
                ('doacao_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacao', to='recebedores.recebedores')),
                ('recebedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebedor_doacao', to='recebedores.recebedores')),
            ],
        ),
    ]
