# Generated by Django 5.0.7 on 2024-08-26 20:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0004_doacao'),
        ('doador', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='doacao_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacao', to='doacao.doacao_item'),
        ),
        migrations.CreateModel(
            name='Doacao_Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgencia', models.CharField(choices=[('LEVE', 'leve'), ('MEDIA', 'media'), ('URGENTE', 'urgente')], max_length=50)),
                ('modo_entrega', models.CharField(choices=[('PRESENCIAL', 'presencial'), ('DELIVERY', 'delivery')], max_length=50)),
                ('status_doacao', models.CharField(choices=[('ACORDADO', 'acordado'), ('ENTREGUE', 'entergue'), ('CANCELADO', 'cancelado')], max_length=50)),
                ('data_recebimento', models.DateTimeField(default=datetime.datetime.now)),
                ('doacao_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacao', to='doacao.item_doacao_rec')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doadores', to='doador.doadores')),
            ],
        ),
    ]
