# Generated by Django 5.0.7 on 2024-08-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0005_alter_doacao_doacao_item_doacao_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao_rec',
            name='doacao_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doacao_pedido', to='doacao.doacao'),
        ),
    ]
