# Generated by Django 5.0.7 on 2024-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0008_alter_doacao_rec_doacao_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='status_doacao',
            field=models.CharField(choices=[('ABERTO', 'aberto'), ('FINALIZADO', 'finalizado'), ('CANCELADO', 'cancelado')], default='aberto', max_length=50),
        ),
    ]
