# Generated by Django 5.0.7 on 2024-09-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0009_alter_doacao_status_doacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='status_doacao',
            field=models.CharField(default='aberto', max_length=50),
        ),
    ]
