# Generated by Django 5.0.7 on 2024-09-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0010_alter_doacao_status_doacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao_rec',
            name='doacao_pedido',
        ),
        migrations.RemoveField(
            model_name='doacao_item',
            name='item',
        ),
        migrations.RemoveField(
            model_name='doacao_rec',
            name='doacao_item',
        ),
        migrations.RemoveField(
            model_name='doacao_rec',
            name='doador',
        ),
        migrations.RemoveField(
            model_name='item_doacao_rec',
            name='Item',
        ),
        migrations.DeleteModel(
            name='Doacao',
        ),
        migrations.DeleteModel(
            name='Doacao_Item',
        ),
        migrations.DeleteModel(
            name='Doacao_Rec',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Item_Doacao_Rec',
        ),
    ]
