# Generated by Django 5.0.7 on 2024-09-06 14:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doacao', '0011_remove_doacao_rec_doacao_pedido_and_more'),
        ('doador', '0007_initial'),
        ('recebedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_item', models.CharField(max_length=255)),
                ('tp_item', models.CharField(choices=[('COMIDA', 'comida'), ('ROUPA', 'roupa'), ('BRINQUEDOS', 'brinquedos'), ('HIGIENE', 'higiene'), ('BRINQUEDOS', 'brinquedos')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgencia', models.CharField(choices=[('LEVE', 'leve'), ('MEDIA', 'media'), ('URGENTE', 'urgente')], max_length=50)),
                ('modo_entrega', models.CharField(choices=[('PRESENCIAL', 'presencial'), ('DELIVERY', 'delivery')], max_length=50)),
                ('status_doacao', models.CharField(default='aberto', max_length=50)),
                ('data_abertura', models.DateTimeField(default=datetime.datetime.now)),
                ('quantidade', models.IntegerField()),
                ('recebedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebedor_doacao', to='recebedores.recebedores')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_doacao', to='doacao.item')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao_Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_entrega', models.CharField(choices=[('PRESENCIAL', 'presencial'), ('DELIVERY', 'delivery')], max_length=50)),
                ('data_recebimento', models.DateTimeField(default=datetime.datetime.now)),
                ('doacao_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacao_pedido', to='doacao.doacao')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doadores', to='doador.doadores')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='doacao.item')),
            ],
        ),
    ]
