# Generated by Django 5.0.7 on 2024-09-06 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0013_alter_item_tp_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao_rec',
            name='data_combinada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
