# Generated by Django 5.0.7 on 2024-09-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0014_doacao_rec_data_combinada'),
        ('doador', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoacaoRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_entrega', models.CharField(max_length=50)),
                ('data_combinada', models.DateTimeField()),
                ('data_recebimento', models.DateTimeField()),
                ('quantidade', models.IntegerField()),
                ('doacao_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacao_pedido', to='doacao.doacao')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doadores', to='doador.doadores')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doacao.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Doacao_Rec',
        ),
    ]
