# Generated by Django 5.0.7 on 2024-09-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0016_rename_data_recebimento_doacaorec_data_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaorec',
            name='data_rec',
            field=models.DateTimeField(default='01/01/2000'),
        ),
    ]
