# Generated by Django 5.0.7 on 2024-09-09 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0019_alter_doacaorec_data_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaorec',
            name='data_rec',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
