# Generated by Django 5.0.7 on 2024-08-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doador',
        ),
    ]
