# Generated by Django 5.0.7 on 2024-08-22 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doador', '0006_delete_doador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_doador', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('cep', models.CharField(default='00000000', max_length=8)),
                ('telefone', models.CharField(max_length=13)),
                ('historico_doacoes', models.IntegerField(verbose_name=models.CharField(default=0))),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
