# Generated by Django 5.0.7 on 2024-09-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0008_doadores_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='historico_doacoes',
            field=models.IntegerField(default=0),
        ),
    ]
