# Generated by Django 5.0.7 on 2024-11-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0009_alter_doadores_historico_doacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='cep',
            field=models.CharField(default='00000000', max_length=9),
        ),
    ]
