# Generated by Django 5.0.7 on 2024-08-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_remove_instituicao_user_delete_doador_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
